### PR TITLE
Add all properties

### PR DESCRIPTION
**Pull request by Explosion-Scratch**

### CODE REVIEW

**Comment by msarca** [comment]
There is a reason we didn't do this so far: constructable stylesheets are supported only in Chromium-based browsers. That's approximately 80% of the web, which is good. But for Safari and FF, we need to pre-generate a set of CSS rules for each assembler property. To avoid FOUC and other issues with layout, we generate 10 rules for each property. This PR increases the number of pre-generated rules, for FF and Safari, from ~1500 to ~4000. That's a huge leap! We need to make more performance tests and measure the impact.

**Comment by Awilum** [comment]
@msarca I didn't get this...

We can't have all css properties in the asmcss core by default ?

**Comment by msarca** [comment]
> We can't have all css properties in the asmcss core by default ?

No, we definitely can, but I don't know if we should. At least not without performance tests. IMHO the best place to complain about this is Firefox and Safari . They are the ones refusing to step into the 21st century, not us.

**Comment by Explosion-Scratch** [comment]
> > We can't have all css properties in the asmcss core by default ?
> 
> No, we definitely can, but I don't know if we should. At least not without performance tests. IMHO the best place to complain about this is Firefox and Safari . They are the ones refusing to step into the 21st century, not us.

What if we keep it how it is, but provide an alternate system for css properties that aren't already accounted for by asmcss, and just compile anything, this could possibly mean the removal of the properties list altogether, right (except for prefixing)? E.g. `sadkjaskldja.hover: blue` would compile to `el:hover { sadkjaskldja: blue }`, even if the `sadkjaskldja` property is nonexistent and not supported by any browser.

**Comment by Awilum** [comment]
It is not good that ASMCSS does not support all CSS properties by default. How we should know, what properties should be provided by default, and what properties should provide via plugins or via any other ways? 

When I started work with a framework, I was supposed to have the ability to work with all CSS properties and not with some random CSS properties list.

Example:

this is works:
```html
<div style="writing-mode: vertical-lr;">
  <div>
    Lorem ipsum dolor, sit amet consectetur adipisicing elit.
  </div>
  <div>
    Lorem ipsum dolor, sit amet consectetur adipisicing elit.
  </div>
</div>
```

but this is not:
```html
<div x-style="writing-mode: vertical-lr;">
  <div>
    Lorem ipsum dolor, sit amet consectetur adipisicing elit.
  </div>
  <div>
    Lorem ipsum dolor, sit amet consectetur adipisicing elit.
  </div>
</div>
```

I hope ASMCSS will able to support all css properties as native `style` do.

**Comment by Explosion-Scratch** [comment]
> I hope ASMCSS `x-style` will able to support all CSS properties as native `style` do.

When I started learning ASMCSS I was under the impression that it _did_, is the library simply striving to get to this?

> The implications of this simple fact are mind-blowing: if you have ever used the `style` attribute, you already know how to use Assembler CSS.

Either way, that's a bit misleading, it would be cool if assembler did support every property, and wouldn't that make the code _shorter_?

**Comment by msarca** [comment]
https://asmcss.com/docs/1.x/assembler-properties.html#register-new-properties

Until Safari and Firefox evolve, this is the only viable solution.

**Pull request closed without merging**
